name: Run Tests on PRs

on:
  pull_request:
    branches:
      - main
  merge_group:
    types: [ checks_requested ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
          cache: npm

      - name: Install packages
        run: npm install

      - name: Run the unit tests
        run: npm run test:ci